env: "local"
storage:
  connection_string: "host=localhost port=5001 user=postgres password=admin dbname=golang_users sslmode=disable"
  migration_path: "./migrations"
grpc:
  port: 44044
  timeout: 5s
jwt:
  token_ttl: 1h
  token_secret: "dawsdawsd"
minio:
  endpoint : "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "mybucket"

